---
- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags: docker

- name: Add Docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Verify Docker GPG key fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags: docker

- name: Add Docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable'
    state: present
    update_cache: yes
  tags: docker

- name: Update apt packages cache
  apt:
    update_cache: yes
  tags: docker

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  tags: docker

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  tags: docker

- name: Install latest Docker Compose
  shell: >
    curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)"
    -o /usr/local/bin/docker-compose
  args:
    executable: /bin/bash
  tags: docker

- name: Set execute permission for Docker Compose
  file:
    path: /usr/local/bin/docker-compose
    mode: '0755'
  tags: docker

- name: Reset SSH connection to apply docker group changes
  meta: reset_connection
